server:
  port: 8081

spring:
  application:
    name: identity-service
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5433/umevent_identity}
    username: ${DATABASE_USERNAME:admin}
    password: ${DATABASE_PASSWORD:admin}
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: identity-service

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
