server:
  port: 8084

spring:
  application:
    name: planning-service
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5433/umevent_planning}
    username: ${DATABASE_USERNAME:admin}
    password: ${DATABASE_PASSWORD:admin}
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: planning-service

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
